dids:
  - &me "did:plc:ivqrehafyybffh7yxmwhf5n5"
  - &me_ua "did:plc:gt4dgeuazvhn4z2hgw4ylkm6"

listRefs:
  - &singal
    did: *me
    rkey: "3ld4s7b56zh2u"

lists:
  - name: Followers of Jesse Singal
    <<: *singal
    entries:
      union:
        - did: "did:plc:232eprew2nyn75ensoah2lg2"
        - followers: "did:plc:232eprew2nyn75ensoah2lg2"
  - name: Blocked by Scalzi
    did: *me_ua
    rkey: 3k53kpqaspl2r
    entries:
      blockedBy: "did:plc:qvzn322kmcvd7xtnips5xaun"
